In [0]:
from google.colab import files
uploaded = files.upload()

Saving train.csv to train.csv


In [0]:
!pip install flair

     |████████████████████████████████| 143kB 1.4MB/s 
     |████████████████████████████████| 133kB 46.8MB/s 
     |████████████████████████████████| 798kB 43.3MB/s 
     |████████████████████████████████| 655kB 42.6MB/s 
     |████████████████████████████████| 1.0MB 36.0MB/s 
  Created wheel for sqlitedict: filename=sqlitedict-1.6.0-cp36-none-any.whl size=14689 sha256=d2c01fa098caa3060d5b956559608a2cdd1964405330d92962bd3101001a151a
  Stored in directory: /root/.cache/pip/wheels/bd/57/d3/907c3ee02d35e66f674ad0106e61f06eeeb98f6ee66a6cc3fe
  Created wheel for mpld3: filename=mpld3-0.3-cp36-none-any.whl size=116679 sha256=20c625f6e15a71f8610214a23e8bff959380944913d0aff3963b474bacb1d3bd
  Stored in directory: /root/.cache/pip/wheels/c0/47/fb/8a64f89aecfe0059830479308ad42d62e898a3e3cefdf6ba28
  Created wheel for segtok: filename=segtok-1.5.7-cp36-none-any.whl size=23257 sha256=72532823d964d7ecc1552b777adfa5dbc971578494e8a3e3b0ccc635a1964dbd
  Stored in directory: /root/.cache/pip/wheels/15

In [0]:
# download flair library #
import torch
import flair

In [0]:
import pandas as pd
df=pd.read_csv("train.csv")

In [0]:
from flair.embeddings import WordEmbeddings
from flair.embeddings import CharacterEmbeddings
from flair.embeddings import StackedEmbeddings
from flair.embeddings import FlairEmbeddings
from flair.embeddings import BertEmbeddings
from flair.embeddings import ELMoEmbeddings
from flair.embeddings import FlairEmbeddings

### Initialising embeddings (un-comment to use others) ###
#glove_embedding = WordEmbeddings('glove')
#character_embeddings = CharacterEmbeddings()
flair_forward  = FlairEmbeddings('news-forward-fast')
flair_backward = FlairEmbeddings('news-backward-fast')
#bert_embedding = BertEmbedding()
#elmo_embedding = ElmoEmbedding()
stacked_embeddings = StackedEmbeddings( embeddings = [ 
                                                       flair_forward, 
                                                       flair_backward
                                                      ])

2019-08-09 05:53:57,046 https://s3.eu-central-1.amazonaws.com/alan-nlp/resources/embeddings/lm-news-english-forward-1024-v0.2rc.pt not found in cache, downloading to /tmp/tmp6ndkf496


100%|██████████| 19689779/19689779 [00:01<00:00, 12300159.46B/s]

2019-08-09 05:53:59,170 copying /tmp/tmp6ndkf496 to cache at /root/.flair/embeddings/lm-news-english-forward-1024-v0.2rc.pt
2019-08-09 05:53:59,199 removing temp file /tmp/tmp6ndkf496


2019-08-09 05:54:00,688 https://s3.eu-central-1.amazonaws.com/alan-nlp/resources/embeddings/lm-news-english-backward-1024-v0.2rc.pt not found in cache, downloading to /tmp/tmpomciym3a


100%|██████████| 19689779/19689779 [00:01<00:00, 12672217.71B/s]

2019-08-09 05:54:02,812 copying /tmp/tmpomciym3a to cache at /root/.flair/embeddings/lm-news-english-backward-1024-v0.2rc.pt
2019-08-09 05:54:02,841 removing temp file /tmp/tmpomciym3a


In [0]:
df['para']='nan'

In [0]:
for i in range(len(df['statement'])):
  df['para'][i]=str(df['statement'][i])+str(df['justification'])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [0]:
df['para'][0]

'Building a wall on the U.S.-Mexico border will take literally years.0       Meantime, engineering experts agree the wall w...\n1       She cited layoff notices received by the state...\n2       Trump said that McCain "has done nothing to he...\n3       But spending still goes up. In addition, many ...\n4       Our rating A Democratic Party web video making...\n5       Rhode Islands former top cop is setting his ba...\n6       Residents in those suburbs do not get a vote b...\n7       Boehner may be technically correct that Biden ...\n8       Speaking at the Democratic National Convention...\n9       Pence said, "We know that more than half of Hi...\n10      While more people voted Democrat in the 2008 p...\n11      We informed Mackowiak of the date conflict. He...\n12      The word "Denali" doesnt show up in Swahili, o...\n13      A social-media meme says that 57 percent of fe...\n14      He clearly has some misgivings about residency...\n15      In October, it was 4. 4 percent, accor

In [0]:
#Data Cleaning for Train, Val, Test
text = df['para'] 

txt = text.tolist()
for i in range(0,len(txt)):
    txt[i] = str(txt[i]).replace('.*([0-9]\.[0-9]+)',"")
    
for i in range(0,len(txt)):
    txt[i] = txt[i].lower()
    
import re
for i in range(0,len(txt)):
    txt[i] = txt[i].replace('\d+', '')
    
import string
for i in range(0,len(txt)):
    txt[i] = re.sub(r'[^\w\s]','',txt[i])
for i in range(0,len(txt)):
    txt[i] = re.sub(r'[^\w\s]','',txt[i])
for i in range(0,len(txt)):
    txt[i] = txt[i].strip()
    
import nltk
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('english')

from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer 
lemmatizer = WordNetLemmatizer() 
for i in range(0, len(txt)):
    tx = word_tokenize(txt[i])
    new_txt = []
    for word in tx:
        new_txt.append(lemmatizer.lemmatize(word))
    txt[i] = ' '.join(word for word in new_txt)
    
from string import digits 
def remove(liste):
    remove_digits = str.maketrans('', '', digits) 
    liste = [i.translate(remove_digits) for i in liste] 
    return liste
txt = remove(txt)

from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize 
nltk.download('stopwords')
for i in range(0, len(txt)):
    stop_words = set(stopwords.words('english')) 
    word_tokens = word_tokenize(txt[i]) 
    filtered_sentence = [] 
    for w in word_tokens: 
        if w not in stop_words: 
            filtered_sentence.append(w) 
    txt[i] = txt[i] = ' '.join(word for word in filtered_sentence)
df['new_txt'] = txt

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
[nltk_data] Error loading english: Package 'english' not found in
[nltk_data]     index
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [0]:
df['new_txt']

0       building wall usmexico border take literally y...
1       wisconsin pace double number layoff year meant...
2       say john mccain ha done nothing help vets mean...
3       suzanne bonamici support plan cut choice medic...
4       asked reporter whether center criminal scheme ...
5       past five year federal government ha paid mill...
6       say tennessee law requires school receive half...
7       say vice president joe biden admits american p...
8       donald trump marriage equality want go back me...
9       know half hillary clinton meeting wa secretary...
10      know democrat georgia republican know fact mea...
11      politifact texas say congressman edward attack...
12      denali kenyan word black power meantime engine...
13      say percent federal spending go military perce...
14      residency requirement public workers meantime ...
15      say unemployment rate college graduate percent...
16      unfortunately documented instance people defec...
17      recent

In [0]:
from flair.data import Sentence
# create a sentence #
sentence = Sentence(df['new_txt'][0])
# embed words in sentence #
stacked_embeddings.embed(sentence)
for token in sentence:
    print(token.embedding)
# data type and size of embedding #
print(type(token.embedding))
# storing size (length) #
z = token.embedding.size()[0]

tensor([ 1.3490e-04, -1.1316e-07,  2.0418e-04,  ..., -2.6223e-09,
         2.4225e-06,  1.9222e-03])
tensor([-1.4859e-03,  1.3796e-07,  8.7510e-06,  ..., -7.7119e-10,
        -1.7263e-04,  8.9308e-03])
tensor([-9.2427e-04, -1.1762e-06,  1.9339e-06,  ..., -5.4239e-09,
         9.8419e-06,  1.1478e-02])
tensor([-6.7796e-04,  4.9776e-05,  1.6533e-05,  ..., -1.5648e-07,
        -5.9845e-04,  3.1040e-02])
tensor([-9.2777e-04, -5.2725e-06,  1.9599e-06,  ..., -4.3400e-09,
        -6.1597e-05,  4.6833e-02])
tensor([ 6.4172e-04, -9.4818e-08,  5.9275e-04,  ..., -1.2363e-09,
        -1.1050e-05,  2.9816e-03])
tensor([-3.4795e-04,  1.3104e-08,  1.6778e-06,  ..., -1.4956e-08,
         1.6365e-04,  1.0753e-02])
tensor([-1.9088e-02,  2.9133e-07,  6.5613e-06,  ..., -6.1943e-09,
         1.1163e-05,  9.3199e-02])
tensor([-4.0483e-03, -6.3222e-05,  9.7681e-06,  ..., -1.3029e-08,
         7.1860e-06,  1.8973e-03])
tensor([-4.7953e-03,  6.9970e-06,  7.3591e-07,  ...,  3.0604e-08,
         1.3528e-04,  2.7

In [0]:
from tqdm import tqdm ## tracks progress of loop ##

# creating a tensor for storing sentence embeddings #
s = torch.zeros(0,z)

# iterating Sentence (tqdm tracks progress) #

for tweet in tqdm(df['new_txt']):
    # empty tensor for words #
    w = torch.zeros(0,z)   
    sentence = Sentence(tweet)
    stacked_embeddings.embed(sentence)
  # for every word #
    for token in sentence:
        # storing word Embeddings of each word in a sentence #
        w = torch.cat((w,token.embedding.view(-1,z)),0)
  # storing sentence Embeddings (mean of embeddings of all words)   #
    s = torch.cat((s, w.mean(dim = 0).view(-1, z)),0)

100%|██████████| 1267/1267 [2:08:33<00:00,  6.51s/it]


In [0]:
X = s.numpy()

In [0]:
from pandas import DataFrame
kane = DataFrame.from_records(X)
kane

0             1         2     ...          2045      2046      2047
0    -0.008703  1.568519e-06  0.000019  ... -6.092151e-08 -0.000072  0.023266
1    -0.008771  1.660799e-06  0.000017  ... -6.177299e-08 -0.000073  0.022930
2    -0.008635  1.358037e-06  0.000017  ... -6.212105e-08 -0.000077  0.023121
3    -0.008698  1.370005e-06  0.000017  ... -6.216437e-08 -0.000069  0.022895
4    -0.008659  1.632138e-06  0.000016  ... -6.003636e-08 -0.000068  0.023294
5    -0.008562  8.052116e-07  0.000018  ... -6.552879e-08 -0.000067  0.023670
6    -0.008585  1.381460e-06  0.000016  ... -6.016857e-08 -0.000237  0.023150
7    -0.008695  1.365912e-06  0.000020  ... -6.235726e-08 -0.000074  0.022858
8    -0.008777  5.317683e-07  0.000017  ... -6.063664e-08 -0.000073  0.023550
9    -0.008655  1.384481e-06  0.000017  ... -6.350393e-08 -0.000069  0.023443
10   -0.008913  1.469437e-06  0.000017  ... -7.187336e-08 -0.000072  0.022879
11   -0.008948  1.420490e-06  0.000017  ... -6.035648e-08 -0.000078  0.022953
12   -0.008960  1.207614e-06  0.000017  ... -6.071335e-08 -0.000074  0.023227
13   -0.008747  6.173743e-07  0.000018  ... -5.883689e-08 -0.000074  0.023846
14   -0.008933  1.424193e-06  0.000018  ... -6.340522e-08 -0.000071  0.022938
15   -0.008738  1.533407e-06  0.000017  ... -5.963637e-08 -0.000072  0.023531
16   -0.008703  1.416318e-06  0.000019  ... -6.890054e-08 -0.000071  0.023196
17   -0.008603  1.276886e-06  0.000017  ... -6.526403e-08 -0.000073  0.022996
18   -0.009491  1.743216e-06  0.000017  ... -6.267978e-08 -0.000063  0.023483
19   -0.008696  1.882784e-06  0.000017  ... -6.261175e-08 -0.000068  0.022979
20   -0.008895 -3.312279e-07  0.000017  ... -6.218523e-08 -0.000067  0.022902
21   -0.008697  1.407575e-06  0.000017  ... -7.714321e-08 -0.000038  0.023517
22   -0.008737  1.372381e-06  0.000017  ... -6.819762e-08 -0.000079  0.022909
23   -0.008789  1.436943e-06  0.000017  ... -6.217033e-08 -0.000078  0.022991
24   -0.009026  5.760995e-07  0.000017  ... -6.039008e-08 -0.000068  0.024981
25   -0.008857  5.947741e-07  0.000017  ... -6.177331e-08 -0.000064  0.024267
26   -0.008920  1.354805e-06  0.000017  ... -6.199898e-08 -0.000060  0.024697
27   -0.008705  1.003332e-06  0.000017  ... -6.133786e-08 -0.000054  0.022928
28   -0.008736  1.446045e-06  0.000018  ... -6.109706e-08 -0.000056  0.022787
29   -0.008594  1.406083e-06  0.000017  ... -6.557976e-08 -0.000074  0.023716
...        ...           ...       ...  ...           ...       ...       ...
1237 -0.008911  1.276011e-06  0.000017  ... -6.079432e-08 -0.000070  0.023223
1238 -0.008557 -1.253615e-07  0.000018  ... -5.881851e-08 -0.000060  0.022784
1239 -0.008849  1.308268e-06  0.000017  ... -6.207986e-08 -0.000071  0.023055
1240 -0.008658  1.041568e-06  0.000017  ... -6.234429e-08 -0.000083  0.023278
1241 -0.009062  6.861449e-07  0.000017  ... -7.165486e-08 -0.000083  0.023741
1242 -0.008936  6.648343e-07  0.000017  ... -6.132336e-08 -0.000073  0.023884
1243 -0.008704  1.388743e-06  0.000017  ... -6.036812e-08 -0.000063  0.023440
1244 -0.008820  1.475068e-06  0.000017  ... -6.175471e-08 -0.000074  0.023145
1245 -0.008741  1.536322e-06  0.000017  ... -6.185672e-08 -0.000069  0.023264
1246 -0.008671  1.475380e-06  0.000017  ... -5.964036e-08 -0.000073  0.023037
1247 -0.008667  1.414501e-06  0.000017  ... -6.073530e-08 -0.000068  0.023145
1248 -0.008674  6.314509e-07  0.000017  ... -6.435265e-08 -0.000071  0.023709
1249 -0.008767  1.415207e-06  0.000017  ... -6.029446e-08 -0.000072  0.023089
1250 -0.008773  1.436118e-06  0.000017  ... -5.993937e-08 -0.000083  0.023393
1251 -0.008707  9.785621e-07  0.000017  ... -6.136849e-08 -0.000065  0.022861
1252 -0.008905  1.391900e-06  0.000017  ... -5.984002e-08 -0.000060  0.022847
1253 -0.008709  1.437435e-06  0.000018  ... -6.261999e-08 -0.000077  0.023084
1254 -0.008814  1.419738e-06  0.000017  ... -5.973870e-08 -0.000080  0.023151
1255 -0.008790  1.675707e-06  0.000017  ... -6.283128e-08 -0.000077  0.023197
1256 -0.008572  1.284277e-06  0.

In [0]:
kane.to_csv('all.csv') 